### GET (Retrieve all messages)
GET http://localhost:3000/api/walloftexts

### POST (Send message to the server)
POST http://localhost:3000/walloftexts
Content-Type: application/json; charset=utf-8

{
    "messages":"Test 4"
} 